config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'     
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :groups, only: [:index, :show, :new, :create, :destroy ] 
  resources :payments, only: [:index, :show, :new, :create, :destroy ]

  authenticated :user do
    root :to => 'groups#index', as: :authenticated_root
  end
  # Defines the root path route ("/")
  # root "articles#index"
  root to: "splash#index"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    return unless user.present?

    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
    can :manage, Payment, author_id: user.id
    can :manage, Group, user_id: user.id
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/group.rb
class Group < ApplicationRecord
  has_and_belongs_to_many :payments, dependent: :destroy
  belongs_to :user

  validates :name, :icon, presence: true
  validates :name, presence: true
  validates :description, length: { maximum: 255 }

  def total_amount
    payments.sum(:amount)
  end

  def most_recent_group_payment
    payments.order(created_at: :desc).first
  end

  def most_ancient_group_payment
    payments.order(created_at: :asc).first
  end
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_and_belongs_to_many :groups, dependent: :destroy

  validates :name, :amount, presence: true
  validates :amount, numericality: { greater_than: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :groups, dependent: :destroy
  has_many :payments, dependent: :destroy

  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def route_not_found
    render file: 'public/404.html', status: :not_found, layout: false
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name photo email])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[name photo email])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @groups = Group.where(user_id: current_user.id).order('created_at DESC')
  end

  def show
    @group = Group.find(params[:id])
    @payments = @group.payments.order('created_at DESC')
  end

  def new
    @group = Group.new
  end

  def create
    @group = current_user.groups.new(group_params)
    if @group.save
      redirect_to groups_path
    else
      render :new
    end
  end

  def destroy
    @group = Group.find(params[:id])
    @group.destroy
    redirect_to groups_path
  end

  private

  def group_params
    params.require(:group).permit(:name, :icon, :description)
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  def index
    redirect_to groups_path
  end

  def new
    @payment = Payment.new
    # @groups = Group.where(user: current_user)
  end

  def create
    @payment = Payment.create(payment_params)
    @payment.author = current_user

    respond_to do |format|
      if @payment.save
        format.html { redirect_to @payment.groups.first, notice: 'Payment was successfully created.' }
        format.json { render :show, status: :created, location: @payment }
      else
        format.html { render :new }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @payment = Payment.find(params[:id])
    @payment.destroy
    redirect_to groups_path
  end

  private

  def payment_params
    params.require(:payment).permit(:name, :amount, group_ids: [])
  end
end

app/controllers/splash_controller.rb
class SplashController < ApplicationController
  skip_before_action :authenticate_user!
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/index.html.erb
  <div class="blue-header">
    <h3 class="text-center">TRANSACTIONS</h3>

    <div class="blue-header-buttom">
       <% if user_signed_in? %>
    <h5><%= link_to "Sign-out", destroy_user_session_path, method: :delete, class: "color-white" %></h5>
   <% end %>
    </div>
    
  </div>
  
  <div class="groups-header">
   <p>Gift credit</p>
   <p>$45</p>
  </div>

 <div class="groups-container">
  <% if @groups.any? %> 
  <% @groups.each do |group| %>
   <div class="group-card">

    <div class="group-icon">
    <p><img src="<%= group.icon%>", class="group-icon-img" /></p>
    </div>

    
   <div class="card-right">
    <div class="name-and-amount">
      <h3><%= link_to group.name, group %></h3>
      <p>$<%= group.total_amount %></p>
    </div>

    <div class="created-at-group">
      <p><%= group.created_at.strftime("%B %d, %Y") %></p>
      <% if can? :destroy, group %>
      <p><%= button_to "Delete", group, method: :delete, data: { confirm: "Are you sure?" }, class: "delete-btn" %></p>
      <% end %>
    </div>
   </div>  
    
   </div>
  <% end %>
  <% else %>
    <p>No groups yet</p>
    <% end %>

  <div class="add-new-category text-center">
  <%= link_to "Add new category", new_group_path, class: "color-white" %>
  </div>

</div>

app/views/groups/new.html.erb
<div class="blue-header header-item">
  <h2><%= link_to "<", groups_path, class: "color-white" %></h2> 
</div>

<div class="sign-in-page">
 <%= form_with scope: :group, url: groups_path, local: true do |form| %>

  <div class="form-label">
    <%= form.text_field :name, placeholder: "Name", class: "input-sign-in" %>
  </div>
  <hr>
  <hr>
  <div class="form-label">
    <%= form.text_field :icon, placeholder: "Add Icon", class: "input-sign-in" %>
  </div>  
  <hr>
  <hr>
  <div class="form-label">
    <%= form.text_field :description, placeholder: "Description", class: "input-sign-in" %>
  </div> 
  <br>

  <div class="form-label">
    <%= form.submit "create", class: "sign-up-btn" %>
  </div>

    <% end %>
</div>

app/views/groups/show.html.erb
<div class="blue-header-show">
 <h2><%= link_to "<", groups_path, class: "color-white" %> </h2>
 <h3 class="text-center">DETAILS</h3>
</div>

<div class="group-show bg-white">

 <div class="icon-and-name-show">
   <div class="group-icon">
    <p><%= image_tag @group.icon, class: "group-icon-img" %></p>
    </div>
   <h4><%= @group.name %></h4>
 </div>
 <br>
 <div class="group-description">
  <p><%= @group.description %></p>
 </div>
 <br>
 <hr>
 <br>
 <div class="transaction-details">
  <% @payments.each do |payment| %>
  <div class="each-transaction-details">
  <p>Transaction: <%= payment.name %>: $<%= payment.amount %> </p>
  <%= payment.created_at %>  
  </div>
  <% end %>
 </div>
 <br>
 <hr>
 <br>
 <div class="total-payment">
  <p>TOTAL PAYMENT</p>
  <p>$<%= @group.total_amount %></p>   
 </div>
</div>
<br>
<br>

<div class="add-new-transaction-btn text-center">
 <%= link_to "Add new transaction", new_payment_path, class: "color-white" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetNavigant2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/payments/index.html.erb
<h1>payments#index</h1>

app/views/payments/new.html.erb
<div class="blue-header header-item">
  <h2><%= link_to "<", groups_path, class: "color-white" %></h2>  
</div>
<div class="sign-in-page">
    <%= form_with scope: :payment, url: payments_path, local: true do |form| %>
        <div class="label">
            <%= form.text_field :name, class: "input-sign-in", placeholder: "Name" %>
        </div>
        <hr>
        <hr>
        <div class="label">
            <%= form.number_field :amount, class: "input-sign-in", placeholder: "Amount" %>
        </div>
        <hr>
        <hr>
        <div class="label">   
        <%= form.collection_select :group_ids, current_user.groups.order(:name), :id, :name, {}, { class: "select-area", multiple: true, required: true } %>
        </div>
        <br>
        <div class="label">
            <%= form.submit "Add transaction", class: "sign-up-btn" %>
        </div>
    <% end %>

</div>

app/views/splash/index.html.erb
 <div class="text-center position-middle">
    <h2><%= image_tag "logo.png", class: "logo" %></h2>
  </div>
<div class="text-center login-root">
  <div class="root-login-btn">
    <%= link_to "LOGIN", new_user_session_path, class: "color-white" %>
  </div>
  <div class="root-signup-btn">
    <%= link_to "SIGN UP", new_user_registration_path, class: "color-grey"%>
  </div>
</div>